#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

###############################################################################
# COMMIT MESSAGE
#
# @description runs after creating the COMMIT message
# @see https://typicode.github.io/husky/
# @see https://git-scm.com/docs/git-commit#_hooks
###############################################################################

pnpm commitlint --edit $1
