#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

###############################################################################
# PRE COMMIT
#
# @description runs before creating the COMMIT message
# @see https://typicode.github.io/husky/
# @see https://git-scm.com/docs/git-commit#_hooks
###############################################################################

pnpm exec lint-staged

# exec < /dev/tty && node_modules/.bin/cz --hook || true
