###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

web:
  
  - id: "{{package.name}}"
    name: "{{package.name}}"
    type: "browser-extension"
    subtypes:
      - Chrome
      - Firefox
      - Safari
      - Chromiun
      - Brave
      - Opera
      - Edge
    version: "{{package.version}}"
    description: "{{package.description}}"
    homepage: "{{package.homepage}}"
    repo: "{{package.extra.licenseUrl}}"
    license: "{{package.extra.licenseUrl}}"
    tags: "{{package.keywords}}"
    logo: "https://raw.githubusercontent.com/pigeonposse/{{package.name}}/main/docs/logo.png"
    banner: "https://raw.githubusercontent.com/pigeonposse/{{package.name}}/main/docs/header.png"
    status: "active"


###############################################################################
